### ISSUE TITLE
`build.cmd` fails with error and exit code -2146232576

### ISSUE THREAD

**Issue by cartermp** [fable-compiler/fable-suave-scaffold#151]
**Machine info:**

* Windows 10 x86 ENU
* VS Enterprise 2017 d15rel version: 15.4.0 Preview 2.0 [26829.00.d15rel]
* dotnet --version: 2.0.0
* Node.js LTS
* Yarn --version: 0.27.5

Vendors reported `build.cmd` failing with this:

```
1) Fake.UnitTestCommon+FailedTestsException: Expecto test of assembly 'C:\Users\ddltd1\source\repos\fable-suave-scaffold\test\UITests\bin\Debug\net461\UITests.exe' failed. Process finished with exit code -2146232576.
   at Fake.Testing.Expecto.Expecto(FSharpFunc`2 setParams, IEnumerable`1 assemblies) in D:\code\fake\src\app\FakeLib\UnitTest\Expecto\Expecto.fs:line 126
   at FSI_0005.Build.clo@169-15.Invoke(Unit _arg13) in C:\Users\ddltd1\source\repos\fable-suave-scaffold\build.fsx:line 182
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in D:\code\fake\src\app\FakeLib\TargetHelper.fs:line 626
```

![image001](https://user-images.githubusercontent.com/6309070/29899273-9deff9e6-8da7-11e7-8bad-f7e43a30e924.jpg)

**Comment by forki** [comment]
@matthid is this because of rolled back paket 5.92?

**Comment by cartermp** [comment]
Updated title: it appears that everything works if .NET Framework 4.6.2 is installed on the machine.  It was not installed either manually or through the process of running `build.cmd`.

**Comment by forki** [comment]
Yeah this is a major annoyance with dotnet cli

Am 31.08.2017 6:46 vorm. schrieb "Phillip Carter" <notifications@github.com

**Comment by forki** [comment]
@cartermp I know there are work arounds that you need to install net462 on windows. And for Linux you can copy files manually, but can you please ask around if your coworkers want to solve it properly?

**Comment by forki** [comment]
Related info: I assume we could change the server tests to use netcore, but we have the same problem with canopy UI tests here. And AFAIK they don't work on netcore.

**Comment by Mousaka** [comment]
I have the same problem running tests on Linux I believe... But being a F# beginner, that still is quite confused by the .net ecosystem, I'm not sure what you, @forki, mean by "And for Linux you can copy files manually". Could you possibly specify that a bit more in detail for me please. Copy what files from where to where? 
Cheers

Here is the end of the output i get after doing `./build.sh`
https://gist.github.com/Mousaka/62b5bd169e723b949ce4df9d93ff6f10

I have this setup:
Ubuntu 16.04.3 LTS
mono version 5.2.0.2
dotnet 2.0.0
nodejs 4.2.6
yarn install v0.27.5

**Comment by forki** [comment]
The problem is not related to F#, but in general to dotnet cli and building
net462 on Linux. Unfortunately I don't have the url to the ms docs right
now. @enricosada?

Am 03.09.2017 3:41 vorm. schrieb "Kristian Lundström" <
notifications@github.com>:
