### ISSUE TITLE
build.cmd fails behind proxy

### ISSUE THREAD

**Issue by vasily-kirichenko** [fable-compiler/fable-suave-scaffold#64]
```
Running build failed.
Error:
System.Net.WebException: The remote server returned an error: (407) Proxy Authentication Required.
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at System.Net.WebClient.DownloadFile(String address, String fileName)
   at FSI_0005.Build.clo@141-6.Invoke(Unit unitVar)
   at FSI_0005.Build.clo@121-4.Invoke(Unit _arg3)
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 492
```

**Comment by YoLieR** [comment]
@vasily-kirichenko I have the same error here but I'm not behined a proxy. Did you have a solution for this? Or did you just circumvent the proxy?

**Comment by vasily-kirichenko** [comment]
@YoLieR I've given up on suave and fable for now :)

**Comment by YoLieR** [comment]
@vasily-kirichenko haha so bad? I also don't know what the problem is right now.

**Comment by vasily-kirichenko** [comment]
TBH, I don't do any web dev, so it was just a curiosity about that hot reload feature. So I don't care of all this stuff really.
