### ISSUE TITLE
build.cmd fails

### ISSUE THREAD

**Issue by vasily-kirichenko** [fable-compiler/fable-suave-scaffold#66]
```
Paket version 3.36.0
0 seconds - ready.
Building project with version: LocalBuild
Shortened DependencyGraph for Target All:
<== All
   <== RunTests
      <== RenameDrivers
         <== BuildTests
            <== Build
               <== BuildClient
                  <== AssemblyInfo
                     <== InstallClient
                        <== InstallDotNetCore
                           <== Clean

The resulting target order is:
 - Clean
 - InstallDotNetCore
 - InstallClient
 - AssemblyInfo
 - BuildClient
 - Build
 - BuildTests
 - RenameDrivers
 - RunTests
 - All
Starting Target: Clean
Deleting contents of bin
Deleting contents of temp
Deleting contents of docs/output
Deleting contents of ./deploy
Deleting contents of E:\github\fable-suave-1\src\Client\public/bundle
Finished Target: Clean
Starting Target: InstallDotNetCore (==> Clean)
C:\Users\kirichenko.KL\AppData\Local\dotnetcore\dotnet.exe --version
dotnetcli 1.0.0-rc4-004771 already installed
Finished Target: InstallDotNetCore
Starting Target: InstallClient (==> InstallDotNetCore)
C:\Program Files\nodejs\npm.cmd install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
Finished Target: InstallClient
Starting Target: AssemblyInfo (==> InstallClient)
Created AssemblyInfo file "E:\github\fable-suave-1\src\Client\AssemblyInfo.fs".
Created AssemblyInfo file "E:\github\fable-suave-1\src\Server\AssemblyInfo.fs".
Finished Target: AssemblyInfo
Starting Target: BuildClient (==> AssemblyInfo)
C:\Program Files\nodejs\npm.cmd run build

> navigation@1.0.0 build E:\github\fable-suave-1\src\Client
> node ../../node_modules/fable-compiler --target production

fable-compiler 0.7.46: Start compilation...
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn cmd ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! navigation@1.0.0 build: `node ../../node_modules/fable-compiler --target production`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the navigation@1.0.0 build script 'node ../../node_modules/fable-compiler --target production'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the navigation package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ../../node_modules/fable-compiler --target production
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs navigation
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls navigation
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     E:\github\fable-suave-1\src\Client\npm-debug.log
Running build failed.
Error:
System.Exception: Error while running 'C:\Program Files\nodejs\npm.cmd' with args: run build
   at FSI_0005.Build.run'@57-3.Invoke(String message) in E:\github\fable-suave-1\build.fsx:line 57
   at FSI_0005.Build.run'(TimeSpan timeout, String cmd, String args, String dir) in E:\github\fable-suave-1\build.fsx:line 57
   at FSI_0005.Build.run@59.Invoke(String cmd, String args, String dir) in E:\github\fable-suave-1\build.fsx:line 59
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 492

---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target              Duration
------              --------
Clean               00:00:00.0052332
InstallDotNetCore   00:00:00.5821592
InstallClient       00:00:03.5400649
AssemblyInfo        00:00:00.0219934
Total:              00:00:06.2803863
Status:             Failure
---------------------------------------------------------------------
  1) System.Exception: Error while running 'C:\Program Files\nodejs\npm.cmd' with args: run build
   at FSI_0005.Build.run'@57-3.Invoke(String message) in E:\github\fable-suave-1\build.fsx:line 57
   at FSI_0005.Build.run'(TimeSpan timeout, String cmd, String args, String dir) in E:\github\fable-suave-1\build.fsx:line 57
   at FSI_0005.Build.run@59.Invoke(String cmd, String args, String dir) in E:\github\fable-suave-1\build.fsx:line 59
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 492
---------------------------------------------------------------------
```

**Comment by et1975** [comment]
>npm ERR! node v6.10.0
>npm ERR! npm  v3.10.10

@alfonsogarciacaro what are the minimal supported versions again?

**Comment by alfonsogarciacaro** [comment]
@et1975 Now I'm using the one installed in Appveyor: 4.7 https://github.com/fable-compiler/Fable/blob/e66cb7fb073b07d9231c9e315943507f8ac1c5a7/appveyor.yml#L8

**Comment by dsyme** [comment]
I went through and the build works fine for me

> npm@3.10.10 C:\Program Files\nodejs\node_modules\npm

**Comment by alfonsogarciacaro** [comment]
Thanks for the confirmation, @dsyme! Let's close this for now then :+1:
