### ISSUE TITLE
Remote access error on running build.cmd

### ISSUE THREAD

**Issue by YoLieR** [fable-compiler/fable-suave-scaffold#69]
Hi together,

I get the following error when running the `build.cmd` script:

```
System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: An attempt was made to access a socket in a way forbidden by its access permissions 93.184.221.200:443
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at System.Net.WebClient.DownloadFile(String address, String fileName)
   at FSI_0005.Build.clo@141-6.Invoke(Unit unitVar)
   at FSI_0005.Build.clo@121-4.Invoke(Unit _arg3)
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 492
```

@vasily-kirichenko opened a similar issue at #64 however in my case I'm not behind a proxy and the error seams to be about some incorrect permissions.
 
Did you face that problem before or do you know about it? Do you have some hint about how to resolve it?
If you need further information pls let me know.

Thanks in advance.

**Comment by alfonsogarciacaro** [comment]
Hi @YoLieR, this seems to be a problem when downloading the dotnet SDK. I've modified the build script so it doesn't try to download the sdk if it's already installed. Can you please make sure you have installed dotnet sdk 1.0.1? (Can be downloaded from [here](https://github.com/dotnet/core/blob/master/release-notes/download-archives/1.0.4-download.md) and you can check running `dotnet --version`) Then pull latest changes and try again?

**Comment by YoLieR** [comment]
Hi @alfonsogarciacaro thanks for the reply.
I updated my dotnet sdk to 1.0.1 (I had 1.0.0 installed already), pulled and rebuild and now everything is working 👍.
A small note about this in the readme would probably be beneficial for others in the future ;).

Thanks for your help :)

**Comment by forki** [comment]
@YoLieR cool. Can you please send a PR with that note? Would help a lot! thx

**Comment by YoLieR** [comment]
@forki yes of course ... I created a PR.

**Comment by forki** [comment]
Thanks and welcome aboard.

Am 14.03.2017 21:48 schrieb "Steffen Schmid" <notifications@github.com>:

**Comment by YoLieR** [comment]
@forki thanks :)
